export const fontSizeOptions = [
  { label: '12px', value: 'text-xs' },
  { label: '14px', value: 'text-sm' },
  { label: '16px', value: 'text-base' },
  { label: '18px', value: 'text-lg' },
  { label: '20px', value: 'text-xl' },
  { label: '24px', value: 'text-2xl' },
  { label: '30px', value: 'text-3xl' },
  { label: '36px', value: 'text-4xl' },
  { label: '48px', value: 'text-5xl' },
  { label: '60px', value: 'text-6xl' },
  { label: '72px', value: 'text-7xl' },
  { label: '96px', value: 'text-8xl' },
  {
    label: '14px : 16px',
    value: 'text-sm md:text-base',
  },
  {
    label: '18px : 20px',
    value: 'text-lg md:text-xl',
  },
  {
    label: '14px : 16px : 18px',
    value: 'text-sm md:text-base lg:text-lg',
  },
  {
    label: '16px : 18px : 24px',
    value: 'text-base md:text-lg lg:text-xl',
  },
  {
    label: '18px : 20px : 24px',
    value: 'text-lg md:text-xl lg:text-2xl',
  },
  {
    label: '20px : 24px : 30px',
    value: 'text-xl md:text-2xl lg:text-3xl',
  },
  {
    label: '24px : 30px : 36px',
    value: 'text-2xl md:text-3xl lg:text-4xl',
  },
  {
    label: '24px : 36px : 60px',
    value: 'text-3xl md:text-4xl lg:text-6xl',
  },
  {
    label: '30px : 48px : 60px',
    value: 'text-3xl md:text-5xl lg:text-6xl',
  },
  {
    label: '36px : 48px : 60px',
    value: 'text-4xl md:text-5xl lg:text-6xl',
  },
  {
    label: '30px : 48px : 72px',
    value: 'text-3xl md:text-5xl lg:text-7xl',
  },
  {
    label: '36px : 60px : 72px',
    value: 'text-4xl md:text-6xl lg:text-7xl',
  },
  {
    label: '48px : 60px : 72px',
    value: 'text-5xl md:text-6xl lg:text-7xl',
  },
  {
    label: '36px : 60px : 96px',
    value: 'text-4xl md:text-6xl lg:text-8xl',
  },
  {
    label: '48px : 72px : 96px',
    value: 'text-5xl md:text-7xl lg:text-8xl',
  },
];

export const lineHeightOptions = [
  { value: 'leading-none md:leading-none lg:leading-none', label: '1' },
  {
    value: 'leading-[1.15em] md:leading-[1.15em] lg:leading-[1.15em]',
    label: '1.15',
  },
  { value: 'leading-tight md:leading-tight lg:leading-tight', label: '1.25' },
  { value: 'leading-snug md:leading-snug lg:leading-snug', label: '1.375' },
  { value: 'leading-normal md:leading-normal lg:leading-normal', label: '1.5' },
  {
    value: 'leading-relaxed md:leading-relaxed lg:leading-relaxed',
    label: '1.625',
  },
  {
    value: 'leading-[1.8em] md:leading-[1.8em] lg:leading-[1.8em]',
    label: '1.8',
  },
  { value: 'leading-loose md:leading-loose lg:leading-loose', label: '2' },
];

export const radiusOptions = [
  { value: 'rounded-none', label: '0px' },
  { value: 'rounded-sm', label: '2px' },
  { value: 'rounded', label: '4px' },
  { value: 'rounded-md', label: '6px' },
  { value: 'rounded-lg', label: '8px' },
  { value: 'rounded-xl', label: '12px' },
  { value: 'rounded-2xl', label: '16px' },
  { value: 'rounded-3xl', label: '24px' },
  { value: 'rounded-full', label: 'full' },
];

export const maxWidthOptions = [
  { label: 'None', value: 'max-w-none' },
  { label: '320px', value: 'max-w-xs' },
  { label: '384px', value: 'max-w-sm' },
  { label: '448px', value: 'max-w-md' },
  { label: '512px', value: 'max-w-lg' },
  { label: '576px', value: 'max-w-xl' },
  { label: '672px', value: 'max-w-2xl' },
  { label: 'Full', value: 'max-w-full' },
  {
    label: '384px : 672px',
    value: 'max-w-sm md:max-w-2xl',
  },
  {
    label: 'Full : 448px : 512px',
    value: 'max-w-full md:max-w-md lg:max-w-lg',
  },
  {
    label: '320px : 448px : 512px',
    value: 'max-w-xs md:max-w-md lg:max-w-lg',
  },
  {
    label: 'Full : 384px : 576px',
    value: 'max-w-full md:max-w-sm lg:max-w-xl',
  },
  {
    label: 'Full : 448px : 576px',
    value: 'max-w-full md:max-w-md lg:max-w-xl',
  },
  {
    label: '320px : 448px : 576px',
    value: 'max-w-xs md:max-w-md lg:max-w-xl',
  },
  {
    label: 'Full : 512px : 672px',
    value: 'max-w-full md:max-w-lg lg:max-w-2xl',
  },
  {
    label: '384px : 512px : 672px',
    value: 'max-w-sm md:max-w-lg lg:max-w-2xl',
  },
];

export const alignmentOptions = [
  { label: 'Left', value: 'text-left' },
  { label: 'Center', value: 'text-center' },
  { label: 'Right', value: 'text-right' },
  { label: 'Left : Center', value: 'text-left md:text-center' },
  { label: 'Left : Left : Center', value: 'text-left lg:text-center' },
  {
    label: 'Left : Center : Right',
    value: 'text-left md:text-center lg:text-right',
  },
  {
    label: 'Center : Center : Right',
    value: 'text-center lg:text-right',
  },
];

export const objectAlignmentOptions = [
  { label: 'Left', value: '' },
  { label: 'Center', value: 'ml-auto mr-auto' },
  { label: 'Right', value: 'ml-auto' },
  { label: 'Left : Center', value: 'md:ml-auto md:mr-auto' },
  { label: 'Left : Left : Center', value: 'lg:ml-auto lg:mr-auto' },
  {
    label: 'Left : Center : Right',
    value: 'mx-0 : md:ml-auto md:mr-auto : lg:ml-auto lg:mr-0',
  },
  {
    label: 'Center : Center : Right',
    value: 'ml-auto mr-auto lg:ml-auto lg:mr-0',
  },
];

export const gapOptions = [
  { label: '0px', value: 'gap-0' },
  { label: '4px', value: 'gap-1' },
  { label: '8px', value: 'gap-2' },
  { label: '12px', value: 'gap-3' },
  { label: '16px', value: 'gap-4' },
  { label: '20px', value: 'gap-5' },
  { label: '24px', value: 'gap-6' },
  { label: '28px', value: 'gap-7' },
  { label: '32px', value: 'gap-8' },
  { label: '40px', value: 'gap-10' },
  { label: '48px', value: 'gap-12' },
  { label: '64px', value: 'gap-16' },
  { label: '80px', value: 'gap-20' },
  { label: '20px : 24px', value: 'gap-5 md:gap-6' },
  { label: '20px : 28px', value: 'gap-5 md:gap-7' },
  { label: '20px : 28px : 32px', value: 'gap-5 md:gap-7 lg:gap-8' },
  { label: '24px : 32px : 40px', value: 'gap-6 md:gap-8 lg:gap-10' },
  { label: '24px : 40px : 48px', value: 'gap-6 md:gap-10 lg:gap-12' },
  { label: '32px : 40px : 48px', value: 'gap-8 md:gap-10 lg:gap-12' },
  { label: '24px : 40px : 64px', value: 'gap-6 md:gap-10 lg:gap-16' },
  { label: '32px : 48px : 64px', value: 'gap-8 md:gap-12 lg:gap-16' },
  { label: '24px : 48px : 80px', value: 'gap-6 md:gap-12 lg:gap-20' },
  { label: '48px : 64px : 80px', value: 'gap-12 md:gap-16 lg:gap-20' },
];

export const paddingLeftOptions = [
  { label: '0px', value: 'pl-0' },
  { label: '4px', value: 'pl-1' },
  { label: '8px', value: 'pl-2' },
  { label: '12px', value: 'pl-3' },
  { label: '16px', value: 'pl-4' },
  { label: '20px', value: 'pl-5' },
  { label: '24px', value: 'pl-6' },
  { label: '28px', value: 'pl-7' },
  { label: '32px', value: 'pl-8' },
  { label: '40px', value: 'pl-10' },
  { label: '48px', value: 'pl-12' },
  { label: '64px', value: 'pl-16' },
  { label: '80px', value: 'pl-20' },
  { label: '0px : 20px', value: 'pl-0 md:pl-5' },
  { label: '0px : 24px', value: 'pl-0 md:pl-6' },
  { label: '0px : 28px', value: 'pl-0 md:pl-7' },
  { label: '20px : 24px', value: 'pl-5 md:pl-6' },
  { label: '20px : 28px', value: 'pl-5 md:pl-7' },
  { label: '20px : 28px : 32px', value: 'pl-5 md:pl-7 lg:pl-8' },
  { label: '24px : 32px : 40px', value: 'pl-6 md:pl-8 lg:pl-10' },
  { label: '24px : 40px : 48px', value: 'pl-6 md:pl-10 lg:pl-12' },
  { label: '32px : 40px : 48px', value: 'pl-8 md:pl-10 lg:pl-12' },
  { label: '20px : 32px : 64px', value: 'pl-6 md:pl-10 lg:pl-16' },
  { label: '24px : 40px : 64px', value: 'pl-6 md:pl-10 lg:pl-16' },
  { label: '32px : 48px : 64px', value: 'pl-8 md:pl-12 lg:pl-16' },
  { label: '24px : 48px : 80px', value: 'pl-6 md:pl-12 lg:pl-20' },
  { label: '48px : 64px : 80px', value: 'pl-12 md:pl-16 lg:pl-20' },
];

export const paddingRightOptions = [
  { label: '0px', value: 'pr-0' },
  { label: '4px', value: 'pr-1' },
  { label: '8px', value: 'pr-2' },
  { label: '12px', value: 'pr-3' },
  { label: '16px', value: 'pr-4' },
  { label: '20px', value: 'pr-5' },
  { label: '24px', value: 'pr-6' },
  { label: '28px', value: 'pr-7' },
  { label: '32px', value: 'pr-8' },
  { label: '40px', value: 'pr-10' },
  { label: '48px', value: 'pr-12' },
  { label: '64px', value: 'pr-16' },
  { label: '80px', value: 'pr-20' },
  { label: '0px : 20px', value: 'pr-0 md:pr-5' },
  { label: '0px : 24px', value: 'pr-0 md:pr-6' },
  { label: '0px : 28px', value: 'pr-0 md:pr-7' },
  { label: '20px : 24px', value: 'pr-5 md:pr-6' },
  { label: '20px : 28px', value: 'pr-5 md:pr-7' },
  { label: '20px : 28px : 32px', value: 'pr-5 md:pr-7 lg:pr-8' },
  { label: '24px : 32px : 40px', value: 'pr-6 md:pr-8 lg:pr-10' },
  { label: '24px : 40px : 48px', value: 'pr-6 md:pr-10 lg:pr-12' },
  { label: '32px : 40px : 48px', value: 'pr-8 md:pr-10 lg:pr-12' },
  { label: '20px : 32px : 64px', value: 'pr-6 md:pr-10 lg:pr-16' },
  { label: '24px : 40px : 64px', value: 'pr-6 md:pr-10 lg:pr-16' },
  { label: '32px : 48px : 64px', value: 'pr-8 md:pr-12 lg:pr-16' },
  { label: '24px : 48px : 80px', value: 'pr-6 md:pr-12 lg:pr-20' },
  { label: '48px : 64px : 80px', value: 'pr-12 md:pr-16 lg:pr-20' },
];

export const paddingTopOptions = [
  { label: '0px', value: 'pt-0' },
  { label: '4px', value: 'pt-1' },
  { label: '8px', value: 'pt-2' },
  { label: '12px', value: 'pt-3' },
  { label: '16px', value: 'pt-4' },
  { label: '20px', value: 'pt-5' },
  { label: '24px', value: 'pt-6' },
  { label: '28px', value: 'pt-7' },
  { label: '32px', value: 'pt-8' },
  { label: '40px', value: 'pt-10' },
  { label: '48px', value: 'pt-12' },
  { label: '64px', value: 'pt-16' },
  { label: '80px', value: 'pt-20' },
  { label: '20px : 24px', value: 'pt-5 md:pt-6' },
  { label: '20px : 28px', value: 'pt-5 md:pt-7' },
  { label: '20px : 28px : 32px', value: 'pt-5 md:pt-7 lg:pt-8' },
  { label: '24px : 32px : 40px', value: 'pt-6 md:pt-8 lg:pt-10' },
  { label: '24px : 40px : 48px', value: 'pt-6 md:pt-10 lg:pt-12' },
  { label: '32px : 40px : 48px', value: 'pt-8 md:pt-10 lg:pt-12' },
  { label: '20px : 32px : 64px', value: 'pt-6 md:pt-10 lg:pt-16' },
  { label: '24px : 40px : 64px', value: 'pt-6 md:pt-10 lg:pt-16' },
  { label: '32px : 48px : 64px', value: 'pt-8 md:pt-12 lg:pt-16' },
  { label: '24px : 48px : 80px', value: 'pt-6 md:pt-12 lg:pt-20' },
  { label: '48px : 64px : 80px', value: 'pt-12 md:pt-16 lg:pt-20' },
];

export const paddingBottomOptions = [
  { label: '0px', value: 'pb-0' },
  { label: '4px', value: 'pb-1' },
  { label: '8px', value: 'pb-2' },
  { label: '12px', value: 'pb-3' },
  { label: '16px', value: 'pb-4' },
  { label: '20px', value: 'pb-5' },
  { label: '24px', value: 'pb-6' },
  { label: '28px', value: 'pb-7' },
  { label: '32px', value: 'pb-8' },
  { label: '40px', value: 'pb-10' },
  { label: '48px', value: 'pb-12' },
  { label: '64px', value: 'pb-16' },
  { label: '80px', value: 'pb-20' },
  { label: '20px : 24px', value: 'pb-5 md:pb-6' },
  { label: '20px : 28px', value: 'pb-5 md:pb-7' },
  { label: '20px : 28px : 32px', value: 'pb-5 md:pb-7 lg:pb-8' },
  { label: '24px : 32px : 40px', value: 'pb-6 md:pb-8 lg:pb-10' },
  { label: '24px : 40px : 48px', value: 'pb-6 md:pb-10 lg:pb-12' },
  { label: '32px : 40px : 48px', value: 'pb-8 md:pb-10 lg:pb-12' },
  { label: '20px : 32px : 64px', value: 'pb-6 md:pb-10 lg:pb-16' },
  { label: '24px : 40px : 64px', value: 'pb-6 md:pb-10 lg:pb-16' },
  { label: '32px : 48px : 64px', value: 'pb-8 md:pb-12 lg:pb-16' },
  { label: '24px : 48px : 80px', value: 'pb-6 md:pb-12 lg:pb-20' },
  { label: '48px : 64px : 80px', value: 'pb-12 md:pb-16 lg:pb-20' },
];

export const borderWidthOptions = [
  { label: '0px', value: 'border-0' },
  { label: '1px', value: 'border' },
  { label: '2px', value: 'border-2' },
  { label: '4px', value: 'border-4' },
  { label: '8px', value: 'border-8' },
  { label: '0px : 1px', value: 'border-0 md:border' },
  { label: '0px : 2px', value: 'border-0 md:border-2' },
  { label: '0px : 4px', value: 'border-0 md:border-4' },
  { label: '0px : 8px', value: 'border-0 md:border-8' },
  { label: '1px : 8px', value: 'border md:border-8' },
  { label: '0px : 1px : 8px', value: 'border-0 md:border lg:border-8' },
  { label: '0px : 2px : 4px', value: 'border-0 md:border-2 lg:border-4' },
  { label: '1px : 2px : 4px', value: 'border md:border-2 lg:border-4' },
  { label: '2px : 4px : 8px', value: 'border-2 md:border-4 lg:border-8' },
  { label: '1px : 4px : 8px', value: 'border md:border-4 lg:border-8' },
];
export const borderTopWidthOptions = [
  { label: '0px', value: 'border-t-0' },
  { label: '1px', value: 'border-t' },
  { label: '2px', value: 'border-t-2' },
  { label: '4px', value: 'border-t-4' },
  { label: '8px', value: 'border-t-8' },
  { label: '0px : 1px', value: 'border-t-0 md:border-t' },
  { label: '0px : 2px', value: 'border-t-0 md:border-t-2' },
  { label: '0px : 4px', value: 'border-t-0 md:border-t-4' },
  { label: '0px : 8px', value: 'border-t-0 md:border-t-8' },
  { label: '1px : 8px', value: 'border-t md:border-t-8' },
  { label: '0px : 1px : 8px', value: 'border-t-0 md:border-t lg:border-t-8' },
  { label: '0px : 2px : 4px', value: 'border-t-0 md:border-t-2 lg:border-t-4' },
  { label: '1px : 2px : 4px', value: 'border-t md:border-t-2 lg:border-t-4' },
  { label: '2px : 4px : 8px', value: 'border-t-2 md:border-t-4 lg:border-t-8' },
  { label: '1px : 4px : 8px', value: 'border-t md:border-t-4 lg:border-t-8' },
];
export const borderBottomWidthOptions = [
  { label: '0px', value: 'border-b-0' },
  { label: '1px', value: 'border-b' },
  { label: '2px', value: 'border-b-2' },
  { label: '4px', value: 'border-b-4' },
  { label: '8px', value: 'border-b-8' },
  { label: '0px : 1px', value: 'border-b-0 md:border-b' },
  { label: '0px : 2px', value: 'border-b-0 md:border-b-2' },
  { label: '0px : 4px', value: 'border-b-0 md:border-b-4' },
  { label: '0px : 8px', value: 'border-b-0 md:border-b-8' },
  { label: '1px : 8px', value: 'border-b md:border-b-8' },
  { label: '0px : 1px : 8px', value: 'border-b-0 md:border-b lg:border-b-8' },
  { label: '0px : 2px : 4px', value: 'border-b-0 md:border-b-2 lg:border-b-4' },
  { label: '1px : 2px : 4px', value: 'border-b md:border-b-2 lg:border-b-4' },
  { label: '2px : 4px : 8px', value: 'border-b-2 md:border-b-4 lg:border-b-8' },
  { label: '1px : 4px : 8px', value: 'border-b md:border-b-4 lg:border-b-8' },
];
export const borderLeftWidthOptions = [
  { label: '0px', value: 'border-l-0' },
  { label: '1px', value: 'border-l' },
  { label: '2px', value: 'border-l-2' },
  { label: '4px', value: 'border-l-4' },
  { label: '8px', value: 'border-l-8' },
  { label: '0px : 1px', value: 'border-l-0 md:border-l' },
  { label: '0px : 2px', value: 'border-l-0 md:border-l-2' },
  { label: '0px : 4px', value: 'border-l-0 md:border-l-4' },
  { label: '0px : 8px', value: 'border-l-0 md:border-l-8' },
  { label: '1px : 8px', value: 'border-l md:border-l-8' },
  { label: '0px : 1px : 8px', value: 'border-l-0 md:border-l lg:border-l-8' },
  { label: '0px : 2px : 4px', value: 'border-l-0 md:border-l-2 lg:border-l-4' },
  { label: '1px : 2px : 4px', value: 'border-l md:border-l-2 lg:border-l-4' },
  { label: '2px : 4px : 8px', value: 'border-l-2 md:border-l-4 lg:border-l-8' },
  { label: '1px : 4px : 8px', value: 'border-l md:border-l-4 lg:border-l-8' },
];
export const borderRightWidthOptions = [
  { label: '0px', value: 'border-r-0' },
  { label: '1px', value: 'border-r' },
  { label: '2px', value: 'border-r-2' },
  { label: '4px', value: 'border-r-4' },
  { label: '8px', value: 'border-r-8' },
  { label: '0px : 1px', value: 'border-r-0 md:border-r' },
  { label: '0px : 2px', value: 'border-r-0 md:border-r-2' },
  { label: '0px : 4px', value: 'border-r-0 md:border-r-4' },
  { label: '0px : 8px', value: 'border-r-0 md:border-r-8' },
  { label: '1px : 8px', value: 'border-r md:border-r-8' },
  { label: '0px : 1px : 8px', value: 'border-r-0 md:border-r lg:border-r-8' },
  { label: '0px : 2px : 4px', value: 'border-r-0 md:border-r-2 lg:border-r-4' },
  { label: '1px : 2px : 4px', value: 'border-r md:border-r-2 lg:border-r-4' },
  { label: '2px : 4px : 8px', value: 'border-r-2 md:border-r-4 lg:border-r-8' },
  { label: '1px : 4px : 8px', value: 'border-r md:border-r-4 lg:border-r-8' },
];

export const borderStyleOptions = [
  { label: 'Solid', value: 'border-solid' },
  { label: 'Dashed', value: 'border-dashed' },
  { label: 'Dotted', value: 'border-dotted' },
  { label: 'Double', value: 'border-double' },
];

export const shadowStyleOptions = [
  { label: 'Shadow none', value: 'shadow-none' },
  { label: 'Shadow one', value: 'shadow-one' },
  { label: 'Shadow sm', value: 'shadow-sm' },
  { label: 'Shadow', value: 'shadow' },
  { label: 'Shadow md', value: 'shadow-md' },
  { label: 'Shadow lg', value: 'shadow-lg' },
  { label: 'Shadow xl', value: 'shadow-xl' },
  { label: 'Shadow 2xl', value: 'shadow-2xl' },
  { label: 'Shadow inner', value: 'shadow-inner' },
];

export const opacityStyles = [
  { label: '0', value: '0' },
  { label: '10', value: '0.10' },
  { label: '20', value: '0.20' },
  { label: '30', value: '0.30' },
  { label: '40', value: '0.40' },
  { label: '50', value: '0.50' },
  { label: '60', value: '0.60' },
  { label: '70', value: '0.70' },
  { label: '80', value: '0.80' },
  { label: '90', value: '0.90' },
  { label: '100', value: '100' },
];